packages:
  - 'master-slave/*'
  - 'reports/*'
  - 'docs/slides'
  - 'packages/*'

allowBuilds:
  '@serialport/bindings-cpp': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  sqlite3: true

overrides:
  markdown-it: "14.3.2"
